## Линейная алгебра.
### Урок 7. Системы линейных уравнений. Часть 2.

In [18]:
import numpy as np

#### 1. Решить систему уравнений методом Крамера:

а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$det A = \begin{vmatrix}
1 & -2\\
3 & -4
\end{vmatrix} = -4 + 6 = 2$  

$det A_1 = \begin{vmatrix}
1 & -2\\
7 & -4
\end{vmatrix} = -4 + 14 = 10$  

$det A_2 = \begin{vmatrix}
1 & 1\\
3 & 7
\end{vmatrix} = 7 - 3 = 4$  

$x_1=\frac{det A_1}{det A}=5$  
$x_2=\frac{det A_2}{det A}=2$

In [19]:
a = np.array([[1,-2],[3,-4]])
a1 = np.array([[1,-2],[7,-4]])
a2 = np.array([[1,1],[3,7]])
print(f'х1 = {np.linalg.det(a1)/np.linalg.det(a):.0f}')
print(f'х2 = {np.linalg.det(a2)/np.linalg.det(a):.0f}')

х1 = 5
х2 = 2


б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$det A = \begin{vmatrix}
2 & -1 & 5\\
1 & 1 & -3\\
2 & 4 & 1
\end{vmatrix} = 2 + 6 + 20 + 24 + 1 - 10 = 43$

$det A_1 = \begin{vmatrix}
10 & -1 & 5\\
-2 & 1 & -3\\
1 & 4 & 1
\end{vmatrix} = 10 + 3 - 40 - 5 - 2 + 120 = 86$

$det A_2 = \begin{vmatrix}
2 & 10 & 5\\
1 & -2 & -3\\
2 & 1 & 1
\end{vmatrix} = -4 -60 +5 +20 -10 +6 = -43$

$det A_3 = \begin{vmatrix}
2 & -1 & 10\\
1 & 1 & -2\\
2 & 4 & 1
\end{vmatrix} = 2 + 4 + 40 - 20 + 1 + 16 = 43$

$x_1=\frac{det A_1}{det A}=2$  
$x_2=\frac{det A_2}{det A}=-1$  
$x_3=\frac{det A_3}{det A}=1$

In [20]:
b = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
b2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
b3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'х1 = {np.linalg.det(b1)/np.linalg.det(b):.0f}')
print(f'х2 = {np.linalg.det(b2)/np.linalg.det(b):.0f}')
print(f'х2 = {np.linalg.det(b3)/np.linalg.det(b):.0f}')

х1 = 2
х2 = -1
х2 = 1


#### 2. Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

$U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 7 & 2\\
0 & 0 & 0 & 5
\end{pmatrix}$

$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 4 & 1 & 0\\
4 & 6 & 3 & 1
\end{pmatrix}$

#### 3. Решить систему линейных уравнений методом $LU$-разложения

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$

$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$

$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & \frac{-23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}$

$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3 & -23 \\ 
0 & 0 & \frac{52}{9}
\end{pmatrix}$

$L=\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{2} & 1
\end{pmatrix}$

$Ly=b$

$\begin{cases}
y_{1}=1, \\
\frac{11}{2}y_{1}+y_{2}=-6, \\
\frac{9}{2}y_{1}+ \frac{7}{2}y_{2}+y_{3}=-5.
\end{cases}$  
$y_{1} = 1,$  
$y_{2}=-6 -\frac{11}{2} =11.5$  
$y_{3}=-5-\frac{9}{2} - \frac{7}{2}=-13$

$y_{1}=1$

$y_{2}=-11.5$

$y_{3}= 30.75$

$Ux=y$

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
1.5x_{2}-11.5x_{3}=-11.5 \\
-20x_{3}=30.75
\end{cases}$

$x_1 = -1$

$\begin{cases}
2(-1)+3=1 \\
11(-1)+5=-6 \\
9(-1)+4=-5
\end{cases}$

#### 4. Решить систему линейных уравнений методом Холецкого

$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$

In [21]:
from numpy.linalg import cholesky
a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
ch = cholesky(a)
print(ch)

[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]


$Ly=b$

$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$

$L^{T}x=y:$

$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$  

$x_{1}=6,$  
$x_{2}=-5,$  
$x_{3}=-4.$

#### 5*. Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [22]:
a = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
U, s, VT = np.linalg.svd(a)
V = VT.T
D = np.zeros_like(a, dtype=float)
D[np.diag_indices(min(a.shape))] = s
print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')

Матрица D:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
Матрица U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]
Матрица V:
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]
