# Практическое задание по теме "Введение в линейную алгебру"

## Практическое задание №5

In [0]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
import scipy 
import scipy.linalg

5.1.
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.


In [3]:
e = np.identity(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
a = e*5
a

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [5]:
p = np.linalg.inv(a)
print(p)

[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


5.2.
Вычислите определитель:



In [6]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
round(np.linalg.det(a))

60.0

5.3.
1. Вычислите матрицу, обратную данной:

In [7]:
p = np.linalg.inv(a)
p

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

2. Приведите пример матрицы 4х4, ранг которой равен 1.

In [8]:
a = np.array([[4, 4, 4, 4], [0, 0, 0, 0], [0, 0, 0, 0],[0, 0, 0, 0]])
a

array([[4, 4, 4, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

5.4.
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)


In [9]:
a = np.array([1, 5])
b = np.array([2, 8])
s = np.inner(a,b)
s

42

5.5
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 


In [10]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
v = np.cross(a, b)
np.inner(v,c)

228.5

In [11]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
w = np.cross(b, c)
np.inner(w,a)

228.5

## Практическое задание №6

6.1 Решите линейную систему:

In [12]:
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
B = np.array([12,2,1])
np.linalg.solve(A,B)

array([-9.2       ,  0.9       ,  6.46666667])

6.2 Найдите псевдорешение:

x + 2y – z = 1

3x – 4y = 7

8x – 5y + 2z = 12

2x – 5z = 7

11x +4y – 7z = 15

In [13]:
A = np.array([[1,2,-1],[3,-4,0],[8,-5,2],[2,-5,0],[11,4,-7]])
B = np.array([1,7,12,7,15])
np.linalg.lstsq(A,B)

(array([ 1.15601029, -0.889718  , -0.85029782]),
 array([0.66772534]),
 3,
 array([14.89650167, 10.4695886 ,  2.73531577]))

6.3 Сколько решений имеет линейная система:

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([12, 2, 1])
np.linalg.matrix_rank(A)

2

Система имеет бесконечно много решений

6.4 Вычислите LU-разложение матрицы:

In [16]:
A = np.array([ [1,2,3], [2,16,21], [4,28,73] ])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [17]:
B = np.array([4, 1, 7])
np.linalg.solve(A, B)

array([ 5.12962963, -0.67592593,  0.07407407])

6.5 Найдите нормальное псевдорешение недоопределенной системы:

In [0]:
def Q(x, y):
    return (x**2 + y**2 + z**2)

In [19]:
A = np.array([[1, 2,-1],[8,-5,2]])
B = np.array([1,12])
np.linalg.lstsq(A, B)

(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

6.6 Найдите одно из псевдорешений вырожденной системы:

In [20]:
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [21]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [22]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  3.55271368e-15])

In [23]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 3.92767275e-15])

In [24]:
X = np.append(X1, 0)
print (X)
np.linalg.norm(X)

[1.50000000e+00 3.92767275e-15 0.00000000e+00]


1.499999999999996

In [25]:
np.linalg.norm(np.dot(A, X) - B)

1.224744871391589