## Линейная алгебра.
### Урок 4. Системы линейных уравнений.

In [21]:
import numpy as np

#### 1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}$

$x_{1} = 2$  
$x_{2} = 3$ 

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$

$\lambda = 2$

$\begin{cases}
-x_{1}-6x_{2} = 2x_{1}\\
2x_{1}+6x_{2} = 2x_{2}
\end{cases}$ 

$\begin{cases}
3x_{1} = -6x_{2}\\
2x_{2} = -x_{1}
\end{cases}$  

$\begin{cases}
x_{1} = -2x_{2}\\
2x_{2} = -x_{1}
\end{cases}$ 

$\begin{cases}
x_{1} = -2\\
x_{2} = 1 
\end{cases}$  

v1 = (-2, 1)

$\lambda = 3$

$\begin{cases}
-x_{1}-6x_{2} = 3x_{1}\\
2x_{1}+6x_{2} = 3x_{2}
\end{cases}$

$\begin{cases}
4x_{1} = -6x_{2}\\
2x_{1} = -3x_{2}
\end{cases}$

$\begin{cases}
x_{1} = -\frac{3}{2}x_{2}\\
x_{1} = -\frac{3}{2}x_{2}
\end{cases}$

$\begin{cases}
x_{1} = \frac{3}{2}\\
x_{2} = -1
\end{cases}$

v2 = ($\frac{3}{2}$, -1)

In [27]:
a = np.array([[-1, -6],
              [2, 6]])

v1 = np.array([-2, 1])
v2 = np.array([3/2, -1])

n1 = np.linalg.norm(v1)
n2 = np.linalg.norm(v2)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{np.array([2, 3])}\n')
print(f'Собственные векторы:\n{v1}, {v2}\n')
print(f'Нормированные собственные векторы:\n{v1/n1}, {v2/n2}\n')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2 3]

Собственные векторы:
[-2  1], [ 1.5 -1. ]

Нормированные собственные векторы:
[-0.89442719  0.4472136 ], [ 0.83205029 -0.5547002 ]



In [28]:
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v[:, 0]}, {v[:, 1]}\n')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]

Собственные векторы:
[-0.89442719  0.4472136 ], [ 0.83205029 -0.5547002 ]



#### 2. Дан оператор поворота на 180 градусов, задаваемый матрицей

$ A = \begin{pmatrix} -1 & 0 \\ 0 & -1 \end{pmatrix} $

Показать, что любой вектор является для него собственным.

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}  
\begin{pmatrix}
2\\
1
\end{pmatrix} =
\lambda
\begin{pmatrix}
2\\
1
\end{pmatrix}$

$\Rightarrow
\begin{cases}
\lambda=-1\\ 
\lambda=-1\\
\end{cases}
\Rightarrow
\lambda=-1$

$\Rightarrow
\begin{cases}
\lambda=-1\\ 
\lambda=-1\\
\end{cases}
\Rightarrow
\lambda=-1$

In [29]:
a = np.array([[-1, 0], [0, -1]])

In [30]:
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v[:, 0]}, {v[:, 1]}\n')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]

Собственные векторы:
[1. 0.], [0. 1.]



#### 3. Пусть линейный оператор задан матрицей

$ A = \begin{pmatrix} 1 & 1 \\ -1 & 3 \end{pmatrix} $

Установить, является ли вектор  x=(1,1)  собственным вектором этого линейного оператора.

$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}$  

$\begin{cases}
1 + 1 = 1\cdot\lambda \\ 
-1 + 3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}$

In [31]:
a = np.array([[1, 1], 
              [-1, 3]])
x = np.array([1, 1])
l = np.dot(a, x)
l / x

array([2., 2.])

#### 4. Пусть линейный оператор задан матрицей

$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}$

$\Rightarrow
\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=-12
\end{cases}
$ $\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}$

In [32]:
a = np.array([[0, 3, 0], 
              [3, 0, 0], 
              [0, 0, 3]])
y = np.array([3, -3, -4])
lam = np.dot(a, y)
print(lam)
np.divide(lam, y)
print(f'Ответ: вектор x=(3, -3, -4) не является собственным вектором линейного оператора A.')

[ -9   9 -12]
Ответ: вектор x=(3, -3, -4) не является собственным вектором линейного оператора A.
