## Линейная алгебра.
### Урок 8. Сингулярное разложение матриц.

In [38]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

#### 1. Найти с помощью NumPy SVD для матрицы

$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$

In [39]:
A = np.array([[1,2,0],
             [0,0,5],
             [3,-4,2],
             [1,6,5],
             [0,1,0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [40]:
U, s, V = np.linalg.svd(A)

In [41]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices((min(A.shape)))] = s
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [42]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [43]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07  0.72  0.69]
 [-0.37  0.67 -0.65]
 [-0.93 -0.21  0.31]]


In [44]:
np.dot(np.dot(U, D)[:, 0:3], V)

array([[ 1.,  2., -0.],
       [-0.,  0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [ 0.,  1.,  0.]])

#### 2. Для матрицы из предыдущего задания найти:

а) евклидову норму;

In [45]:
Norma=np.linalg.norm(A, ord=2)
print(f'Евклидова норма: {Norma}')

Евклидова норма: 8.824868854820442


б) норму Фробениуса.

In [46]:
np.linalg.norm(A)

11.045361017187261

In [47]:
NormaF=np.linalg.norm(A, ord='fro')
print(f'Норма Фробениуса: {NormaF}')

Норма Фробениуса: 11.045361017187261


In [48]:
D_squared = np.square(A)
print(f'Норма Фробениуса: {np.sqrt(D_squared.sum())}')

Норма Фробениуса: 11.045361017187261
