## Линейная алгебра.
### Урок 2. Матрицы и матричные операции.

In [23]:
import numpy as np

#### 1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2;  
$AB$ и $BA$ - неопределены (недопустимая операция, нельзя перемножить)

б)  A  — матрица  2×5 ,  B  — матрица  5×3;  
AB - $2\times 3$, BA - неопределена, нельзя перемножить

в)  A  — матрица  8×3 ,  B  — матрица  3×8;  
AB - $8\times 8$, BA - $3\times 3$

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4;  
AB - $4\times 4$, BA - $4\times 4$.

#### 2. Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [24]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Сумма: A + B\n{A + B}')
print(f'Произведение: AB\n{np.dot(A, B)}')

Сумма: A + B
[[ 5 -3]
 [ 3  5]]
Произведение: AB
[[  4 -11]
 [ 12  -3]]


#### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$- $2\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$+ $4\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}$ = $\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$- $\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$+ $\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$ = $\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [25]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2 ,-1]])
C = np.array([[2 ,-4],[1, 1]])

B2 = -2*B

print(f"Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 для матриц 𝐴 = \n{3*A + B2 + 4*C}\n")

Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 для матриц 𝐴 = 
[[ 11  -5]
 [  9 -12]]



#### 4. Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$. Вычислить $AA^{T}$ и $A^{T}A$.

$AA^{T}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$, $A^{T}A=\begin{pmatrix}
45 & 0 \\ 
0 & 14
\end{pmatrix}$.

In [26]:
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T
print(f'Матрица AA^T\n{np.dot(A, AT)}')
print(f'Матрица A^T*A\n{np.dot(AT, A)}')

Матрица AA^T
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A^T*A
[[45  0]
 [ 0 14]]


#### 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [27]:
def matrix_func(matrix_A, matrix_B):
    sum_ = 0     
    matrix_ = []    
    matrix_С = [] 
    if len(matrix_B)!=len(matrix_A[0]): 
        print("Матрицы не могут быть перемножены")       
    else:
        for z in range(0, len(matrix_A)):
            for j in range(0,len(matrix_B[0])):
                for i in range(0,len(matrix_A[0])):
                   sum_ += matrix_A[z][i]*matrix_B[i][j]
                matrix_.append(sum_)
                sum_ = 0
            matrix_С.append(matrix_)
            matrix_ = []           
    return matrix_С

In [28]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
matrix_func(a, b)

[[4, -11], [12, -3]]