## Линейная алгебра.
### Урок 2. Матрицы и матричные операции.

In [17]:
import numpy as np

#### 1. Вычислить определитель:

а) $\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$

$\begin{vmatrix}
sinx ;& -cosx\\ 
cosx ;& sinx
\end{vmatrix} = sinx \cdot sinx + cosx \cdot cosx = sin^2x +  cos^2x = 1$

In [18]:
A = np.array([[4, 1], [5, -2]])
print(f'Определитель: sin^2(x)+cos^2(x) = 1')

Определитель: sin^2(x)+cos^2(x) = 1


б) $\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$

$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180$

In [19]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Определитель: 4 * 5 * 9 = 180')
print(f'Определитель: {np.linalg.det(A):.0f}')

Определитель: 4 * 5 * 9 = 180
Определитель: 180


в) $\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1 \cdot \begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix}  - 2 \cdot \begin{vmatrix}
4  & 6\\ 
7  & 9
\end{vmatrix} + 3 \cdot \begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix} = -3 + 12 - 9 = 0  $

In [20]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель: {np.linalg.det(A):.0f}')

Определитель: 0


#### 2. Определитель матрицы  A  равен  4 . Найти:

а) $det(A^{2}) = det(AA) = |A| \cdot |A| = 4 \cdot 4 = 16$;

б) $det(A^{T}) = det(A)  = 4$;

в) $det(2A) = 2^2 \cdot |A|  = 16 $.

#### 3. Доказать, что матрица вырожденная.

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$

Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.
Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.
Т.к. первая строка = (-2) умножить на вторую строку, т.е. они линейно зависимы, то определитель = 0

$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
3 & 7 & 13
\end{vmatrix} = -2 \cdot \begin{vmatrix}
-14 & 6\\ 
7 & 13
\end{vmatrix}  - 7 \cdot \begin{vmatrix}
4  & 6\\ 
3  & 13
\end{vmatrix} - 3 \cdot \begin{vmatrix}
4 & -14\\ 
3 & 7
\end{vmatrix} = -2 \cdot (-182 -42) -7 \cdot (52 - 18) -3 \cdot (28 + 52) = 448 - 238 - 210 = 0  $

In [21]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель: {np.linalg.det(A):.0f}')

Определитель: 0


#### 4. Найти ранг матрицы:

а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [22]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'{a}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}')

[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [23]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'{b}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(b)}')

[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
